---
title: Chipbälle
author: Lars Maurath
date: '2020-07-04'
slug: chipbälle
categories: []
tags: []
image: ''
showonlyimage: no
---

```{r Load Libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(dbplyr)
library(DBI)
library(cowplot)
```

```{r Matches, echo=FALSE}
team_ids <- c(37)

con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "~/Documents/Blog/Data/data.sqlite")

matches <- tbl(con, "matches") %>%
  #filter(season %in% c("2019/2020", "2018/2019", "2017/2018", "2016/2017", "2015/2016", "2014/2015", "2013/2014", "2012/2013")) %>%
  filter(season %in% c("2019/2020", "2018/2019", "2017/2018")) %>%
  filter(league %in% c("Germany")) %>%
  filter(home_team_id %in% team_ids | away_team_id %in% team_ids) %>%
  select(c("match_id", "season", "league", "date")) %>%
  collect()

DBI::dbDisconnect(con)

match_ids <- matches$match_id

match_summary <- matches %>% 
  group_by(season, league) %>%
  summarise(count = n())
```

```{r Get all Throw-Ins, echo=FALSE}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "~/Documents/Blog/Data/data.sqlite")

chipped <- tbl(con, "events") %>%
  filter(match_id %in% match_ids) %>%
  filter(teamId %in% team_ids) %>%
  filter(type_name == "Pass") %>%
  filter(qualifiers %like% "%Chipped%", qualifiers %like% "%Throughball%", qualifiers %not like% "%Cross%", qualifiers %not like% "%Longball%") %>%
  collect()

DBI::dbDisconnect(con)
```

```{r Enrich Data, echo=FALSE}
chipped_ext <- chipped %>%
  mutate(PassEndX = as.numeric(PassEndX), PassEndY = as.numeric(PassEndY)) %>%
  mutate(into_box = if_else(PassEndX > 83 & (PassEndY > 21.1 & PassEndY < 78.9), TRUE, FALSE)) %>%
  mutate(assist = if_else(grepl("IntentionalGoalAssist", qualifiers), TRUE, FALSE)) %>%
  filter(into_box) %>%
  filter(outcome == "Successful")

chipped_ext <- left_join(chipped_ext, select(matches, "match_id", "season"), by = "match_id") 
```

```{r Naive Pass Plot, echo=FALSE}
source("../data/pitch_plots.r")

pitch <- create_opta_Pitch(grass_colour = "grey10", line_colour = "#8F8F8F", background_colour = "grey10", goal_colour = "#000000", middlethird = TRUE, arcs = FALSE) +
  geom_segment(data = chipped_ext, aes(x = location_x, y = location_y, xend = PassEndX, yend = PassEndY, color = assist), arrow = arrow(length = unit(0.02, "npc"))) + 
  theme(legend.position = "none") +
  draw_image("https://tmssl.akamaized.net/images/portrait/header/31909-1519743952.jpg?lm=1519743979", x = 5.0, y = 10.0, scale = 20) +
  annotate("text", 
           x = 12, 
           y = 10, 
           colour = "grey90", 
           family = "mono",
           size = 2.5, 
           hjust = 0, 
           label = "Toni Kroos \nOpen Play Passes \nChampions League Final \nv Liverpool 2017/2018")

pitch
```